// Color mapping from color_map.csv
const COLOR_MAP = {
    "Sage Green": "#9CAF88",
    "Viridian": "#40826D",
    "Lime Zest": "#C4DA42",
    "Forest Pine": "#295135",
    "Olive Drab": "#6B8E23",
    "Emerald Mist": "#50C878",
    "Seafoam": "#9FE2BF",
    "Cerulean": "#2A52BE",
    "Sky Azure": "#63B8FF",
    "Indigo Ink": "#264066",
    "Cobalt Blue": "#0047AB",
    "Teal Lagoon": "#008080",
    "Prussian Blue": "#003153",
    "Crimson": "#DC143C",
    "Cherry Red": "#D2042D",
    "Vermilion": "#E34234",
    "Brick Rust": "#8B3A3A",
    "Scarlet Hue": "#FF2400",
    "Rosewood": "#65000B",
    "Coral Bloom": "#FF7F50",
    "Sunflower": "#FFC512",
    "Amber Glow": "#FFBF00",
    "Goldenrod": "#DAA520",
    "Marigold": "#FFC300",
    "Mustard Seed": "#D4AF37",
    "Flax Yellow": "#EEDC82",
    "Tangerine": "#F28500",
    "Apricot": "#FBCEB1",
    "Persimmon": "#EC5800",
    "Burnt Sienna": "#E97451",
    "Copper Penny": "#AD6F69",
    "Pumpkin Spice": "#D77A2F",
    "Lavender": "#B57EDC",
    "Amethyst": "#9966CC",
    "Mauve Dust": "#E0B0FF",
    "Periwinkle": "#CCCCFF",
    "Violet Night": "#4B0082",
    "Magenta Fuchsia": "#FF00FF",
    "Blush Pink": "#FFC0CB",
    "Salmon Rose": "#FA8072",
    "Peony": "#EFA6C0",
    "Mulberry": "#70193D",
    "Burgundy Plum": "#581845",
    "Wine Berry": "#5D3A3A",
    "Slate Gray": "#708090",
    "Charcoal": "#36454F",
    "Smoke Silver": "#C0C0C0",
    "Graphite": "#3B3B3B",
    "Ash Mist": "#D3D3D3",
    "Pebble": "#B0A89F",
    "Sandstone": "#D2B48C",
    "Umber": "#635147"
};

function getColorHex(name) {
    return COLOR_MAP[name] || "#CCCCCC";
}

// Oracle card data converted from ix52-oracle-web.csv
const ORACLE_CARDS = [
    {
        "suit": "Hearts",
        "rank": "Ace",
        "card_code": "hearts_ace",
        "card_label": "Ace of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Sage Green",
        "hex": "#9CAF88",
        "lucky_number": 44,
        "rank_archetype": "beginnings • seed potential",
        "quote": "Softness is not weakness; it is structural courage.",
        "oracle_text": "Let the heart set the tone; a small act of honesty opens the river.",
        "mantra": "I open softly to truth.",
        "tiny_action": "Send one genuine message of appreciation.",
        "journal_prompt": "Where can I speak one true feeling today?",
        "body_cue": "Chair sit‑to‑stands — 3×10",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors beginnings • seed potential.",
        "word_of_the_day": "aporia",
        "word_meaning": "state of puzzlement inviting inquiry",
        "trivia": "Dolphins use signature whistles as names.",
        "trivia_source": "Royal Society — https://royalsocietypublishing.org",
        "bipolar_self_check": "Morning check‑in: Rate stability 1–10 (D–S–M). 1–3 = depressed tilt, 4–7 = stable, 8–10 = manic tilt."
    },
    {
        "suit": "Hearts",
        "rank": "2",
        "card_code": "hearts_2",
        "card_label": "Two of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Viridian",
        "hex": "#40826D",
        "lucky_number": 16,
        "rank_archetype": "duality • choice",
        "quote": "Compassion without clarity turns to fog.",
        "oracle_text": "Hold two truths gently—yours and theirs; balance breeds peace.",
        "mantra": "I hold two truths without hardening.",
        "tiny_action": "State a feeling + a need in one sentence.",
        "journal_prompt": "Which boundary keeps my heart soft, not hard?",
        "body_cue": "Wall push‑ups — 3×8",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors duality • choice.",
        "word_of_the_day": "limen",
        "word_meaning": "threshold; point of entering a new state",
        "trivia": "The brain uses ~20% of resting energy.",
        "trivia_source": "Scientific American — https://www.scientificamerican.com",
        "bipolar_self_check": "Energy audit: Is energy > mood? If yes, slow your pace by 10% and schedule a pause."
    },
    {
        "suit": "Hearts",
        "rank": "3",
        "card_code": "hearts_3",
        "card_label": "Three of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Lime Zest",
        "hex": "#C4DA42",
        "lucky_number": 21,
        "rank_archetype": "growth • weaving",
        "quote": "What you tend, tends you.",
        "oracle_text": "Weave care with others; let support circulate.",
        "mantra": "I weave care and let it circulate.",
        "tiny_action": "Schedule a 10‑min check‑in with one ally.",
        "journal_prompt": "Who are my three allies today—and how will I nourish them?",
        "body_cue": "Calf raises — 3×15",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors growth • weaving.",
        "word_of_the_day": "ananke",
        "word_meaning": "inescapable necessity; fate",
        "trivia": "Quarantine\" comes from \"quaranta giorni\".",
        "trivia_source": "CDC Museum — https://www.cdc.gov",
        "bipolar_self_check": "Clarity scan: Are thoughts racing or sticky? Note it in one sentence without judgment."
    },
    {
        "suit": "Hearts",
        "rank": "4",
        "card_code": "hearts_4",
        "card_label": "Four of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Forest Pine",
        "hex": "#295135",
        "lucky_number": 22,
        "rank_archetype": "structure • rest",
        "quote": "Still waters store power.",
        "oracle_text": "Rest is resistance; protect your inner well.",
        "mantra": "I protect my calm waters.",
        "tiny_action": "Block 20 mins for quiet breathing/journaling.",
        "journal_prompt": "What simple ritual calms my water?",
        "body_cue": "Glute bridges — 3×12",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors structure • rest.",
        "word_of_the_day": "telos",
        "word_meaning": "an end or ultimate purpose",
        "trivia": "Trees share resources via fungal networks.",
        "trivia_source": "Ecology Letters — https://onlinelibrary.wiley.com",
        "bipolar_self_check": "Sleep log: How many hours last night? Under 6 or over 10—flag with a star in your log."
    },
    {
        "suit": "Hearts",
        "rank": "5",
        "card_code": "hearts_5",
        "card_label": "Five of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Olive Drab",
        "hex": "#6B8E23",
        "lucky_number": 4,
        "rank_archetype": "friction • change",
        "quote": "Anger is unspent protection; give it a task.",
        "oracle_text": "Emotional weather shifts; ride the wave without lashing out.",
        "mantra": "I ride the wave, not the storm.",
        "tiny_action": "Name the feeling; pause 5 minutes before replying.",
        "journal_prompt": "How can I express anger without harm?",
        "body_cue": "Bird‑dog — 2×8/side",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors friction • change.",
        "word_of_the_day": "kairos",
        "word_meaning": "the opportune, decisive moment",
        "trivia": "Ancient Mesopotamia left early musical notation.",
        "trivia_source": "British Museum — https://www.britishmuseum.org",
        "bipolar_self_check": "Medication check: Took meds as prescribed? If missed, log time and resume plan—no doubling."
    },
    {
        "suit": "Hearts",
        "rank": "6",
        "card_code": "hearts_6",
        "card_label": "Six of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Emerald Mist",
        "hex": "#50C878",
        "lucky_number": 38,
        "rank_archetype": "flow • reciprocity",
        "quote": "Circulation is the heartbeat of abundance.",
        "oracle_text": "Offer what you seek; generosity returns as current.",
        "mantra": "I give freely; currents return.",
        "tiny_action": "Write a thank‑you note.",
        "journal_prompt": "Where can I give a little with no scoreboard?",
        "body_cue": "Dead bug — 2×10",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors flow • reciprocity.",
        "word_of_the_day": "eudaimonia",
        "word_meaning": "flourishing through virtue",
        "trivia": "Everest rises a few millimeters each year.",
        "trivia_source": "USGS — https://www.usgs.gov",
        "bipolar_self_check": "Caffeine cap: Track cups. If >2 today, swap the next with water to prevent overstimulation."
    },
    {
        "suit": "Hearts",
        "rank": "7",
        "card_code": "hearts_7",
        "card_label": "Seven of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Seafoam",
        "hex": "#9FE2BF",
        "lucky_number": 40,
        "rank_archetype": "faith • testing",
        "quote": "Self‑trust is the quietest revolution.",
        "oracle_text": "Test of trust: keep a promise to yourself.",
        "mantra": "I keep promises to my heart.",
        "tiny_action": "Keep one small promise before noon.",
        "journal_prompt": "Which self‑promise needs defending today?",
        "body_cue": "Standing hip hinges — 3×12",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors faith • testing.",
        "word_of_the_day": "ataraxia",
        "word_meaning": "calm freedom from disturbance",
        "trivia": "Orchestras commonly tune to A4=440 Hz.",
        "trivia_source": "Berlin Phil — https://www.berliner-philharmoniker.de",
        "bipolar_self_check": "Irritability signal: Any spikes? Choose one de‑escalation tool (walk, breath, music) for 5 minutes."
    },
    {
        "suit": "Hearts",
        "rank": "8",
        "card_code": "hearts_8",
        "card_label": "Eight of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Cerulean",
        "hex": "#2A52BE",
        "lucky_number": 52,
        "rank_archetype": "power • discipline",
        "quote": "Devotion is disciplined attention.",
        "oracle_text": "Devote attention like prayer; discipline is devotion.",
        "mantra": "I devote my attention with love.",
        "tiny_action": "Replace one doom‑scroll with a 10‑min walk.",
        "journal_prompt": "What emotional habit, if trimmed 1%, frees me most?",
        "body_cue": "Wall sit — 3×30s",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors power • discipline.",
        "word_of_the_day": "noesis",
        "word_meaning": "direct knowing or intellection",
        "trivia": "Titan has rivers and lakes of liquid methane.",
        "trivia_source": "NASA — https://solarsystem.nasa.gov",
        "bipolar_self_check": "Impulse gate: Delay big decisions by 24 hours; leave a note for 'future me.'"
    },
    {
        "suit": "Hearts",
        "rank": "9",
        "card_code": "hearts_9",
        "card_label": "Nine of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Sky Azure",
        "hex": "#63B8FF",
        "lucky_number": 18,
        "rank_archetype": "ripening • integration",
        "quote": "Tender does not mean porous.",
        "oracle_text": "Let tenderness be your armor; integration ≠ overexposure.",
        "mantra": "I am tender and well‑bounded.",
        "tiny_action": "Answer with one clear sentence, then stop.",
        "journal_prompt": "Where am I over‑explaining feelings?",
        "body_cue": "Plank — 3×20–30s",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors ripening • integration.",
        "word_of_the_day": "enantiodromia",
        "word_meaning": "tendency to turn into its opposite",
        "trivia": "Inca quipu recorded data with knots.",
        "trivia_source": "Smithsonian NMAI — https://americanindian.si.edu",
        "bipolar_self_check": "Budget glance: Unplanned spending urge? Freeze cart for 24 hours and review tomorrow."
    },
    {
        "suit": "Hearts",
        "rank": "10",
        "card_code": "hearts_10",
        "card_label": "Ten of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Indigo Ink",
        "hex": "#264066",
        "lucky_number": 10,
        "rank_archetype": "completion • legacy",
        "quote": "Endings are altars for beginnings.",
        "oracle_text": "Close an old story with gratitude, not drama.",
        "mantra": "I release with gratitude.",
        "tiny_action": "Archive one chat/thread you no longer need.",
        "journal_prompt": "What chapter of my heart is ready to end well?",
        "body_cue": "Side plank (knees) — 2×20s/side",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors completion • legacy.",
        "word_of_the_day": "palimpsest",
        "word_meaning": "something reused with traces remaining",
        "trivia": "Red hair links to MC1R gene variants.",
        "trivia_source": "National Geographic — https://www.nationalgeographic.com",
        "bipolar_self_check": "Social meter: Am I avoiding everyone or over‑engaging? Nudge 1 step toward the middle."
    },
    {
        "suit": "Hearts",
        "rank": "Jack",
        "card_code": "hearts_jack",
        "card_label": "Jack of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Cobalt Blue",
        "hex": "#0047AB",
        "lucky_number": 49,
        "rank_archetype": "messenger • student",
        "quote": "Listening edits reality.",
        "oracle_text": "Be curious about others' inner weather.",
        "mantra": "I listen until I truly hear.",
        "tiny_action": "Ask that question to one person.",
        "journal_prompt": "What question would make someone feel seen?",
        "body_cue": "Thoracic 'open book' — 2×10/side",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors messenger • student.",
        "word_of_the_day": "apercu",
        "word_meaning": "a quick, insightful summary",
        "trivia": "Lightning heats air hotter than the Sun's surface.",
        "trivia_source": "NWS — https://www.weather.gov",
        "bipolar_self_check": "Nutrition nudge: Eat protein at the next meal to stabilize energy and mood."
    },
    {
        "suit": "Hearts",
        "rank": "Queen",
        "card_code": "hearts_queen",
        "card_label": "Queen of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Teal Lagoon",
        "hex": "#008080",
        "lucky_number": 3,
        "rank_archetype": "steward • receptivity",
        "quote": "Boundaries are love with structure.",
        "oracle_text": "Hold space without rescuing; compassion has edges.",
        "mantra": "I care with clear edges.",
        "tiny_action": "Offer help with a clear limit: what/when/how long.",
        "journal_prompt": "Where does care turn into control for me?",
        "body_cue": "90/90 hip switches — 2×10",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors steward • receptivity.",
        "word_of_the_day": "psithurism",
        "word_meaning": "sound of wind in leaves",
        "trivia": "Movable type transformed Europe's information flow.",
        "trivia_source": "British Library — https://www.bl.uk",
        "bipolar_self_check": "Screen brake: If doom‑scrolling >15 minutes, switch to a 5‑minute stretch or breath set."
    },
    {
        "suit": "Hearts",
        "rank": "King",
        "card_code": "hearts_king",
        "card_label": "King of Hearts",
        "element": "Water",
        "suit_theme": "emotion & connection",
        "direction": "West",
        "color": "Prussian Blue",
        "hex": "#003153",
        "lucky_number": 37,
        "rank_archetype": "sovereign • direction",
        "quote": "The room breathes at your pace.",
        "oracle_text": "Lead with calm; set the emotional temperature.",
        "mantra": "I set a gentle, steady tone.",
        "tiny_action": "Begin with a two‑sentence intention.",
        "journal_prompt": "What tone do I want the room to borrow from me?",
        "body_cue": "Ankle dorsiflexion rocks — 2×15/side",
        "verbesque_verb": "Restore",
        "verbesque_cue": "Today, Restore your emotion & connection in a way that honors sovereign • direction.",
        "word_of_the_day": "sonder",
        "word_meaning": "realization that others have vivid lives",
        "trivia": "Alexandria's library was likely multiple sites.",
        "trivia_source": "Britannica — https://www.britannica.com",
        "bipolar_self_check": "Sunlight dose: Step outside for 5–10 minutes; note effect on mood (↑/→/↓)."
    },
    {
        "suit": "Diamonds",
        "rank": "Ace",
        "card_code": "diamonds_ace",
        "card_label": "Ace of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Crimson",
        "hex": "#DC143C",
        "lucky_number": 32,
        "rank_archetype": "beginnings • seed potential",
        "quote": "Wealth begins as a well‑kept promise.",
        "oracle_text": "Plant one seed in the material world.",
        "mantra": "I plant one true seed today.",
        "tiny_action": "Transfer ₱100–₱300 to savings or prep one whole‑food snack.",
        "journal_prompt": "What tiny act moves money/body/craft forward?",
        "body_cue": "Chair sit‑to‑stands — 3×10",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors beginnings • seed potential.",
        "word_of_the_day": "kenosis",
        "word_meaning": "self‑emptying to make space",
        "trivia": "The Antikythera mechanism modeled the heavens.",
        "trivia_source": "Nature — https://www.nature.com",
        "bipolar_self_check": "Movement micro‑win: 5–10 minutes gentle movement; log ease vs. effort (E/Ne)."
    },
    {
        "suit": "Diamonds",
        "rank": "2",
        "card_code": "diamonds_2",
        "card_label": "Two of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Cherry Red",
        "hex": "#D2042D",
        "lucky_number": 51,
        "rank_archetype": "duality • choice",
        "quote": "Equilibrium is earned in small choices.",
        "oracle_text": "Balance resources like scales; trade time for traction.",
        "mantra": "I balance resources with ease.",
        "tiny_action": "Do the 10‑minute chore you've delayed.",
        "journal_prompt": "What low‑effort task yields high stability?",
        "body_cue": "Wall push‑ups — 3×8",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors duality • choice.",
        "word_of_the_day": "aleph",
        "word_meaning": "a point holding infinite possibilities",
        "trivia": "A standard piano has 88 keys.",
        "trivia_source": "Steinway — https://www.steinway.com",
        "bipolar_self_check": "Speech pace: Notice speed/volume. Aim for 10% slower and softer if elevated."
    },
    {
        "suit": "Diamonds",
        "rank": "3",
        "card_code": "diamonds_3",
        "card_label": "Three of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Vermilion",
        "hex": "#E34234",
        "lucky_number": 46,
        "rank_archetype": "growth • weaving",
        "quote": "Skill is honest repetition.",
        "oracle_text": "Craft improves in community; iterate openly.",
        "mantra": "I refine my craft in community.",
        "tiny_action": "Share a WIP with one person and ask one question.",
        "journal_prompt": "Who can give me fast feedback on my work?",
        "body_cue": "Calf raises — 3×15",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors growth • weaving.",
        "word_of_the_day": "syzygy",
        "word_meaning": "pairing of opposites; alignment",
        "trivia": "Paper money began in China (Tang/Song).",
        "trivia_source": "Bank of China Museum — https://www.boc.cn/en",
        "bipolar_self_check": "Focus anchor: One‑line intention for the next hour; check alignment at the end."
    },
    {
        "suit": "Diamonds",
        "rank": "4",
        "card_code": "diamonds_4",
        "card_label": "Four of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Brick Rust",
        "hex": "#8B3A3A",
        "lucky_number": 45,
        "rank_archetype": "structure • rest",
        "quote": "Rituals are ethics for the body.",
        "oracle_text": "Stability beats spectacle; build a simple repeatable step.",
        "mantra": "I build simple repeatable steps.",
        "tiny_action": "Set a 2‑item morning setup for work gear/space.",
        "journal_prompt": "Which routine locks in tomorrow's ease?",
        "body_cue": "Glute bridges — 3×12",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors structure • rest.",
        "word_of_the_day": "anagnorisis",
        "word_meaning": "sudden critical recognition",
        "trivia": "Venus rotates retrograde; the Sun rises in its west.",
        "trivia_source": "NASA — https://solarsystem.nasa.gov",
        "bipolar_self_check": "Rumination reroute: If looping, write a 3‑bullet 'facts only' list."
    },
    {
        "suit": "Diamonds",
        "rank": "5",
        "card_code": "diamonds_5",
        "card_label": "Five of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Scarlet Hue",
        "hex": "#FF2400",
        "lucky_number": 35,
        "rank_archetype": "friction • change",
        "quote": "Count clearly, then breathe.",
        "oracle_text": "Scarcity is a story; check the ledger and act, not spiral.",
        "mantra": "I count clearly, then act.",
        "tiny_action": "Cancel/pause one unused subscription.",
        "journal_prompt": "What expense can I cut without pain?",
        "body_cue": "Bird‑dog — 2×8/side",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors friction • change.",
        "word_of_the_day": "praxis",
        "word_meaning": "embodied practice of a theory",
        "trivia": "The kilogram is defined via Planck's constant.",
        "trivia_source": "NIST — https://www.nist.gov",
        "bipolar_self_check": "Joy ping: Name one small thing that felt good today; lock it in with a breath."
    },
    {
        "suit": "Diamonds",
        "rank": "6",
        "card_code": "diamonds_6",
        "card_label": "Six of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Rosewood",
        "hex": "#65000B",
        "lucky_number": 26,
        "rank_archetype": "flow • reciprocity",
        "quote": "Value grows when it moves.",
        "oracle_text": "Circulate value; fair exchange nourishes both sides.",
        "mantra": "I let value move through me.",
        "tiny_action": "Pay one small debt or pre‑commit to a deliverable.",
        "journal_prompt": "Where can I pay promptly or tip generosity?",
        "body_cue": "Dead bug — 2×10",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors flow • reciprocity.",
        "word_of_the_day": "topos",
        "word_meaning": "a recurring theme or commonplace",
        "trivia": "Coffee was once banned in Mecca.",
        "trivia_source": "History.com — https://www.history.com",
        "bipolar_self_check": "Hydration check: Drink a glass of water now; watch for thirst masquerading as anxiety."
    },
    {
        "suit": "Diamonds",
        "rank": "7",
        "card_code": "diamonds_7",
        "card_label": "Seven of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Coral Bloom",
        "hex": "#FF7F50",
        "lucky_number": 29,
        "rank_archetype": "faith • testing",
        "quote": "Pruning is care with a future.",
        "oracle_text": "Audit your garden; prune to strengthen.",
        "mantra": "I prune to strengthen growth.",
        "tiny_action": "Pause one non‑aligned task for after IX:52.",
        "journal_prompt": "Which project is a vanity vine?",
        "body_cue": "Standing hip hinges — 3×12",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors faith • testing.",
        "word_of_the_day": "caliginous",
        "word_meaning": "misty; obscure; dim",
        "trivia": "Octopuses have neurons in their arms for semi‑independent processing.",
        "trivia_source": "Nature — https://www.nature.com",
        "bipolar_self_check": "Boundary pulse: Did I say yes when I meant no? Draft a repair message if needed."
    },
    {
        "suit": "Diamonds",
        "rank": "8",
        "card_code": "diamonds_8",
        "card_label": "Eight of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Sunflower",
        "hex": "#FFC512",
        "lucky_number": 27,
        "rank_archetype": "power • discipline",
        "quote": "Mastery is patient momentum.",
        "oracle_text": "Skill compounds; reps over brilliance.",
        "mantra": "I trust patient, steady reps.",
        "tiny_action": "Do one focused skill block (timer on).",
        "journal_prompt": "What craft drill will I practice for 20 minutes?",
        "body_cue": "Wall sit — 3×30s",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors power • discipline.",
        "word_of_the_day": "vermillion",
        "word_meaning": "a vivid red pigment",
        "trivia": "Bats are the only mammals with sustained flight.",
        "trivia_source": "Bat Conservation Trust — https://www.bats.org.uk",
        "bipolar_self_check": "Plan realism: Compare to capacity. Remove one nonessential task to protect stability."
    },
    {
        "suit": "Diamonds",
        "rank": "9",
        "card_code": "diamonds_9",
        "card_label": "Nine of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Amber Glow",
        "hex": "#FFBF00",
        "lucky_number": 36,
        "rank_archetype": "ripening • integration",
        "quote": "Security feels like softness in the jaw.",
        "oracle_text": "Savor modest wealth: comfort from consistency.",
        "mantra": "I savor enoughness.",
        "tiny_action": "Cook one protein‑forward meal at home.",
        "journal_prompt": "How does my body feel when I'm resourced?",
        "body_cue": "Plank — 3×20–30s",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors ripening • integration.",
        "word_of_the_day": "smaragdine",
        "word_meaning": "emerald‑green",
        "trivia": "Placebo effects change brain activity.",
        "trivia_source": "Harvard Health — https://www.health.harvard.edu",
        "bipolar_self_check": "Evening slope: Rate wind‑down quality 1–10; if <6, choose a 15‑minute calming ritual."
    },
    {
        "suit": "Diamonds",
        "rank": "10",
        "card_code": "diamonds_10",
        "card_label": "Ten of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Goldenrod",
        "hex": "#DAA520",
        "lucky_number": 15,
        "rank_archetype": "completion • legacy",
        "quote": "Systems are kindness across time.",
        "oracle_text": "Think legacy processes, not heroics.",
        "mantra": "I design systems that serve.",
        "tiny_action": "Document a 5‑step SOP.",
        "journal_prompt": "What system lets future‑me thank present‑me?",
        "body_cue": "Side plank (knees) — 2×20s/side",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors completion • legacy.",
        "word_of_the_day": "cerulean",
        "word_meaning": "deep sky‑blue",
        "trivia": "Ravens can plan and barter.",
        "trivia_source": "Science — https://www.science.org",
        "bipolar_self_check": "Support touchpoint: Send a 'no‑need‑to‑reply' update to a trusted person if you're wobbly."
    },
    {
        "suit": "Diamonds",
        "rank": "Jack",
        "card_code": "diamonds_jack",
        "card_label": "Jack of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Marigold",
        "hex": "#FFC300",
        "lucky_number": 19,
        "rank_archetype": "messenger • student",
        "quote": "Ship to learn, not to stun.",
        "oracle_text": "Apprentice mindset: learn by shipping.",
        "mantra": "I learn by shipping small.",
        "tiny_action": "Publish a micro‑deliverable.",
        "journal_prompt": "What's the smallest artifact I can ship today?",
        "body_cue": "Thoracic 'open book' — 2×10/side",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors messenger • student.",
        "word_of_the_day": "argent",
        "word_meaning": "silvery; of silver",
        "trivia": "Tardigrades survive extremes via a tun state.",
        "trivia_source": "ESA — https://www.esa.int",
        "bipolar_self_check": "Catastrophe check: Ask 'What evidence supports this fear?' Write 1 line; breathe out longer."
    },
    {
        "suit": "Diamonds",
        "rank": "Queen",
        "card_code": "diamonds_queen",
        "card_label": "Queen of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Mustard Seed",
        "hex": "#D4AF37",
        "lucky_number": 41,
        "rank_archetype": "steward • receptivity",
        "quote": "The body keeps both score and wisdom.",
        "oracle_text": "Tend the body like sacred land.",
        "mantra": "I tend the body with respect.",
        "tiny_action": "10–15 min mobility or a gentle walk.",
        "journal_prompt": "What kindness does my body request right now?",
        "body_cue": "90/90 hip switches — 2×10",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors steward • receptivity.",
        "word_of_the_day": "umbrageous",
        "word_meaning": "shadowy; easily offended",
        "trivia": "Hoba is the largest intact meteorite on Earth.",
        "trivia_source": "GSA — https://www.geosociety.org",
        "bipolar_self_check": "Future pull: If manic tilt, limit future‑planning sessions to 10 minutes, timer on."
    },
    {
        "suit": "Diamonds",
        "rank": "King",
        "card_code": "diamonds_king",
        "card_label": "King of Diamonds",
        "element": "Earth",
        "suit_theme": "body, money & craft",
        "direction": "North",
        "color": "Flax Yellow",
        "hex": "#EEDC82",
        "lucky_number": 17,
        "rank_archetype": "sovereign • direction",
        "quote": "Constraints are the rails of freedom.",
        "oracle_text": "Steward resources with calm clarity.",
        "mantra": "I steward my resources calmly.",
        "tiny_action": "Set a daily spend cap and log once today.",
        "journal_prompt": "What single constraint guides my spending this week?",
        "body_cue": "Ankle dorsiflexion rocks — 2×15/side",
        "verbesque_verb": "Ground",
        "verbesque_cue": "Today, Ground your body, money & craft in a way that honors sovereign • direction.",
        "word_of_the_day": "liminal",
        "word_meaning": "occupying a boundary or threshold",
        "trivia": "Microplastics occur even in Arctic snow.",
        "trivia_source": "Science — https://www.science.org",
        "bipolar_self_check": "Comfort kit: Choose one sensory soother (shower, blanket, tea) for 5 minutes of grounding."
    },
    {
        "suit": "Clubs",
        "rank": "Ace",
        "card_code": "clubs_ace",
        "card_label": "Ace of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Tangerine",
        "hex": "#F28500",
        "lucky_number": 33,
        "rank_archetype": "beginnings • seed potential",
        "quote": "Courage is a pilot light.",
        "oracle_text": "Spark the flame; one brave move lights the week.",
        "mantra": "I spark momentum with courage.",
        "tiny_action": "Post one imperfect idea publicly.",
        "journal_prompt": "What tiny risk could unlock momentum?",
        "body_cue": "Chair sit‑to‑stands — 3×10",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors beginnings • seed potential.",
        "word_of_the_day": "meraki",
        "word_meaning": "doing something with soul and love",
        "trivia": "Algorithm\" derives from al‑Khwarizmi.",
        "trivia_source": "Stanford Encyclopedia — https://plato.stanford.edu",
        "bipolar_self_check": "Task slicing: If stuck, slice the task into a 5‑minute first slice; do only that."
    },
    {
        "suit": "Clubs",
        "rank": "2",
        "card_code": "clubs_2",
        "card_label": "Two of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Apricot",
        "hex": "#FBCEB1",
        "lucky_number": 7,
        "rank_archetype": "duality • choice",
        "quote": "Focus is fire with a target.",
        "oracle_text": "Aim the fire; scattered sparks don't cook a meal.",
        "mantra": "I aim my fire with focus.",
        "tiny_action": "Pick one focus KPI for today.",
        "journal_prompt": "Which of two paths feeds the bigger story?",
        "body_cue": "Wall push‑ups — 3×8",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors duality • choice.",
        "word_of_the_day": "ikigai",
        "word_meaning": "a reason for being",
        "trivia": "Glass is an amorphous solid.",
        "trivia_source": "Corning Museum — https://www.cmog.org",
        "bipolar_self_check": "Opposite action: If withdrawing, send a hello; if overactive, schedule a 15‑minute stillness."
    },
    {
        "suit": "Clubs",
        "rank": "3",
        "card_code": "clubs_3",
        "card_label": "Three of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Persimmon",
        "hex": "#EC5800",
        "lucky_number": 25,
        "rank_archetype": "growth • weaving",
        "quote": "Make together; shine together.",
        "oracle_text": "Creativity wants collaboration; jam, don't hoard.",
        "mantra": "I create with others.",
        "tiny_action": "Invite a quick brainstorm or co‑edit.",
        "journal_prompt": "Who could riff with me for 15 minutes?",
        "body_cue": "Calf raises — 3×15",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors growth • weaving.",
        "word_of_the_day": "hygeia",
        "word_meaning": "health; personification of wellbeing",
        "trivia": "The Jacquard loom was an early programmable device.",
        "trivia_source": "Science Museum — https://www.sciencemuseum.org.uk",
        "bipolar_self_check": "Reactivity watch: Track the first trigger today and how you responded; note one improvement."
    },
    {
        "suit": "Clubs",
        "rank": "4",
        "card_code": "clubs_4",
        "card_label": "Four of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Burnt Sienna",
        "hex": "#E97451",
        "lucky_number": 23,
        "rank_archetype": "structure • rest",
        "quote": "A frame makes the picture burn brighter.",
        "oracle_text": "Contain the blaze; a frame makes art legible.",
        "mantra": "I frame my blaze to burn bright.",
        "tiny_action": "Block 2×50‑min deep‑work on calendar.",
        "journal_prompt": "What boundary increases my creative heat?",
        "body_cue": "Glute bridges — 3×12",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors structure • rest.",
        "word_of_the_day": "noosphere",
        "word_meaning": "sphere of human thought",
        "trivia": "Adults have ~206 bones; babies ~270 that fuse.",
        "trivia_source": "NIH — https://www.nih.gov",
        "bipolar_self_check": "Media diet: Swap intense content for neutral (nature, crafts) for the next hour."
    },
    {
        "suit": "Clubs",
        "rank": "5",
        "card_code": "clubs_5",
        "card_label": "Five of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Copper Penny",
        "hex": "#AD6F69",
        "lucky_number": 24,
        "rank_archetype": "friction • change",
        "quote": "Play is discipline in disguise.",
        "oracle_text": "Healthy competition sharpens the blade.",
        "mantra": "I turn friction into play.",
        "tiny_action": "Time‑box a task; beat yesterday's time.",
        "journal_prompt": "How can I turn friction into a game?",
        "body_cue": "Bird‑dog — 2×8/side",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors friction • change.",
        "word_of_the_day": "heuristic",
        "word_meaning": "rule of thumb aiding discovery",
        "trivia": "UV light triggers vitamin D production.",
        "trivia_source": "WHO — https://www.who.int",
        "bipolar_self_check": "Self‑talk line: Write one compassionate sentence to yourself and reread it thrice."
    },
    {
        "suit": "Clubs",
        "rank": "6",
        "card_code": "clubs_6",
        "card_label": "Six of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Pumpkin Spice",
        "hex": "#D77A2F",
        "lucky_number": 47,
        "rank_archetype": "flow • reciprocity",
        "quote": "Wind the spring, then let it sing.",
        "oracle_text": "Let momentum carry; share, then step aside.",
        "mantra": "I share and let momentum carry.",
        "tiny_action": "Cross‑post one piece using a template.",
        "journal_prompt": "Which channel amplifies this with least effort?",
        "body_cue": "Dead bug — 2×10",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors flow • reciprocity.",
        "word_of_the_day": "autotelic",
        "word_meaning": "having an end in itself",
        "trivia": "Artemisia Gentileschi was a Baroque master.",
        "trivia_source": "National Gallery — https://www.nationalgallery.org.uk",
        "bipolar_self_check": "Check for grandiosity: Any 'invincible' thoughts? Park them in a note; revisit in 48 hours."
    },
    {
        "suit": "Clubs",
        "rank": "7",
        "card_code": "clubs_7",
        "card_label": "Seven of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Lavender",
        "hex": "#B57EDC",
        "lucky_number": 5,
        "rank_archetype": "faith • testing",
        "quote": "Faith is focus over time.",
        "oracle_text": "Stay with the vision when results lag.",
        "mantra": "I stay loyal to the vision.",
        "tiny_action": "Write a 3‑line manifesto.",
        "journal_prompt": "What doubt visits me most—and what evidence dissolves it?",
        "body_cue": "Standing hip hinges — 3×12",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors faith • testing.",
        "word_of_the_day": "eunoia",
        "word_meaning": "beautiful thinking; goodwill",
        "trivia": "Svalbard holds a global seed vault.",
        "trivia_source": "Crop Trust — https://www.croptrust.org",
        "bipolar_self_check": "Sleep protect: Set a tech cutoff time tonight; note how it affects next‑day clarity."
    },
    {
        "suit": "Clubs",
        "rank": "8",
        "card_code": "clubs_8",
        "card_label": "Eight of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Amethyst",
        "hex": "#9966CC",
        "lucky_number": 28,
        "rank_archetype": "power • discipline",
        "quote": "Remove the damp wood.",
        "oracle_text": "Discipline is your furnace.",
        "mantra": "I feed the furnace with discipline.",
        "tiny_action": "Mute one notification channel for 24h.",
        "journal_prompt": "Which distraction steals the most fire?",
        "body_cue": "Wall sit — 3×30s",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors power • discipline.",
        "word_of_the_day": "anamnesis",
        "word_meaning": "recollection; remembrance",
        "trivia": "Easter Island moai were likely 'walked' with ropes.",
        "trivia_source": "PNAS — https://www.pnas.org",
        "bipolar_self_check": "Noise level: If overstimulated, try 10 minutes of quiet or earplugs; log relief (0–2)."
    },
    {
        "suit": "Clubs",
        "rank": "9",
        "card_code": "clubs_9",
        "card_label": "Nine of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Mauve Dust",
        "hex": "#E0B0FF",
        "lucky_number": 50,
        "rank_archetype": "ripening • integration",
        "quote": "Excess smoke means a cold fire.",
        "oracle_text": "Sustained heat, not burnout.",
        "mantra": "I choose heat without haze.",
        "tiny_action": "Trim one deliverable to its essence.",
        "journal_prompt": "Where can I do less but better?",
        "body_cue": "Plank — 3×20–30s",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors ripening • integration.",
        "word_of_the_day": "apothegm",
        "word_meaning": "a concise instructive saying",
        "trivia": "Negative numbers were long controversial in Europe.",
        "trivia_source": "MacTutor — https://mathshistory.st-andrews.ac.uk",
        "bipolar_self_check": "Stability score: 3 times today (AM/PM/Night) rate 1–10 and draw a tiny arrow trend."
    },
    {
        "suit": "Clubs",
        "rank": "10",
        "card_code": "clubs_10",
        "card_label": "Ten of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Periwinkle",
        "hex": "#CCCCFF",
        "lucky_number": 20,
        "rank_archetype": "completion • legacy",
        "quote": "Weight moves when you drop what isn't yours.",
        "oracle_text": "A big push needs clear shoulders.",
        "mantra": "I carry only what is mine.",
        "tiny_action": "Defer one non‑critical task beyond Day 52.",
        "journal_prompt": "What can I delegate or defer today?",
        "body_cue": "Side plank (knees) — 2×20s/side",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors completion • legacy.",
        "word_of_the_day": "proprioception",
        "word_meaning": "sense of body position",
        "trivia": "The \"butterfly effect\" came from Lorenz's chaos work.",
        "trivia_source": "AMS — https://www.ams.org",
        "bipolar_self_check": "Pace audit: Are you rushing? Add 10% buffer between tasks for recovery."
    },
    {
        "suit": "Clubs",
        "rank": "Jack",
        "card_code": "clubs_jack",
        "card_label": "Jack of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Violet Night",
        "hex": "#4B0082",
        "lucky_number": 48,
        "rank_archetype": "messenger • student",
        "quote": "Signal beats spectacle.",
        "oracle_text": "Messenger energy—ship the story.",
        "mantra": "I ship the story clearly.",
        "tiny_action": "Post a 3‑sentence update.",
        "journal_prompt": "What's the headline version of today's work?",
        "body_cue": "Thoracic 'open book' — 2×10/side",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors messenger • student.",
        "word_of_the_day": "catharsis",
        "word_meaning": "emotional purging",
        "trivia": "Sharks predate trees in the fossil record.",
        "trivia_source": "Natural History Museum — https://www.nhm.ac.uk",
        "bipolar_self_check": "Anger channel: Convert agitation into movement (walk, clean, stretch) for 10 minutes."
    },
    {
        "suit": "Clubs",
        "rank": "Queen",
        "card_code": "clubs_queen",
        "card_label": "Queen of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Magenta Fuchsia",
        "hex": "#FF00FF",
        "lucky_number": 43,
        "rank_archetype": "steward • receptivity",
        "quote": "Consistency is hospitality.",
        "oracle_text": "Warm, steady fire—cultivate audience trust.",
        "mantra": "I warm the room with consistency.",
        "tiny_action": "Reply to 3 comments with care.",
        "journal_prompt": "How do I make followers feel safe to engage?",
        "body_cue": "90/90 hip switches — 2×10",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors steward • receptivity.",
        "word_of_the_day": "pareidolia",
        "word_meaning": "seeing patterns where none exist",
        "trivia": "Honeybees communicate via a \"waggle dance\".",
        "trivia_source": "Smithsonian Magazine — https://www.smithsonianmag.com",
        "bipolar_self_check": "Schedule sanity: Keep appointments under a realistic cap; decline one optional thing."
    },
    {
        "suit": "Clubs",
        "rank": "King",
        "card_code": "clubs_king",
        "card_label": "King of Clubs",
        "element": "Fire",
        "suit_theme": "will, creativity & brand",
        "direction": "South",
        "color": "Blush Pink",
        "hex": "#FFC0CB",
        "lucky_number": 6,
        "rank_archetype": "sovereign • direction",
        "quote": "Leadership is heat without hurry.",
        "oracle_text": "Direct the flame toward the mission.",
        "mantra": "I direct heat toward the mission.",
        "tiny_action": "Say no to one off‑brand ask.",
        "journal_prompt": "What decision simplifies the week?",
        "body_cue": "Ankle dorsiflexion rocks — 2×15/side",
        "verbesque_verb": "Forge",
        "verbesque_cue": "Today, Forge your will, creativity & brand in a way that honors sovereign • direction.",
        "word_of_the_day": "zugzwang",
        "word_meaning": "a forced move worsening position",
        "trivia": "Egyptians helped standardize the 24‑hour day.",
        "trivia_source": "Britannica — https://www.britannica.com",
        "bipolar_self_check": "Mindful micro‑meal: Eat one meal without screens; note fullness and calm (0–2)."
    },
    {
        "suit": "Spades",
        "rank": "Ace",
        "card_code": "spades_ace",
        "card_label": "Ace of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Salmon Rose",
        "hex": "#FA8072",
        "lucky_number": 12,
        "rank_archetype": "beginnings • seed potential",
        "quote": "Clarity is kindness to cognition.",
        "oracle_text": "Cut the fog; name the truth cleanly.",
        "mantra": "I cut fog with one true line.",
        "tiny_action": "Write it at the top of today's notes.",
        "journal_prompt": "What one sentence would simplify everything?",
        "body_cue": "Chair sit‑to‑stands — 3×10",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors beginnings • seed potential.",
        "word_of_the_day": "bricolage",
        "word_meaning": "creation from available materials",
        "trivia": "Arctic terns migrate ~40,000 km annually.",
        "trivia_source": "Audubon — https://www.audubon.org",
        "bipolar_self_check": "Cool down: If elevated, take a lukewarm shower or face splash; observe effect."
    },
    {
        "suit": "Spades",
        "rank": "2",
        "card_code": "spades_2",
        "card_label": "Two of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Peony",
        "hex": "#EFA6C0",
        "lucky_number": 8,
        "rank_archetype": "duality • choice",
        "quote": "Both can be true; choose anyway.",
        "oracle_text": "Hold paradox without panic.",
        "mantra": "I hold paradox and choose.",
        "tiny_action": "Define decision criteria in 3 bullets.",
        "journal_prompt": "Where are two good options fighting?",
        "body_cue": "Wall push‑ups — 3×8",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors duality • choice.",
        "word_of_the_day": "parallax",
        "word_meaning": "apparent shift from a new viewpoint",
        "trivia": "Bamboo can grow >30 cm per day.",
        "trivia_source": "Kew Gardens — https://www.kew.org",
        "bipolar_self_check": "Warmth up: If low, try a warm beverage and sunlight; notice a 1‑point shift."
    },
    {
        "suit": "Spades",
        "rank": "3",
        "card_code": "spades_3",
        "card_label": "Three of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Mulberry",
        "hex": "#70193D",
        "lucky_number": 11,
        "rank_archetype": "growth • weaving",
        "quote": "Some thoughts are scaffolds; remove them.",
        "oracle_text": "Let old ideas die so better ones breathe.",
        "mantra": "I retire spent ideas.",
        "tiny_action": "Retire one rule that no longer serves.",
        "journal_prompt": "What belief is past its expiry date?",
        "body_cue": "Calf raises — 3×15",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors growth • weaving.",
        "word_of_the_day": "serotinous",
        "word_meaning": "late‑blooming; opening with heat",
        "trivia": "A day on Mercury (sunrise‑sunrise) ≈ 176 Earth days.",
        "trivia_source": "NASA — https://www.solarsystem.nasa.gov",
        "bipolar_self_check": "Connection check: Share your 1–10 stability with a trusted person (optional)."
    },
    {
        "suit": "Spades",
        "rank": "4",
        "card_code": "spades_4",
        "card_label": "Four of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Burgundy Plum",
        "hex": "#581845",
        "lucky_number": 9,
        "rank_archetype": "structure • rest",
        "quote": "Silence sharpens the blade.",
        "oracle_text": "Quiet mind, sharp edge.",
        "mantra": "I quiet inputs, sharpen mind.",
        "tiny_action": "Set a 12‑hour social media curfew.",
        "journal_prompt": "Which input diet will clear my head?",
        "body_cue": "Glute bridges — 3×12",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors structure • rest.",
        "word_of_the_day": "sophiology",
        "word_meaning": "love and study of wisdom",
        "trivia": "The wheat and chessboard legend explodes exponentially.",
        "trivia_source": "Plus Magazine — https://plus.maths.org",
        "bipolar_self_check": "Overcommit check: Before saying yes, ask 'Does this protect stability?' Decide accordingly."
    },
    {
        "suit": "Spades",
        "rank": "5",
        "card_code": "spades_5",
        "card_label": "Five of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Wine Berry",
        "hex": "#5D3A3A",
        "lucky_number": 30,
        "rank_archetype": "friction • change",
        "quote": "Debate the idea; defend the edge.",
        "oracle_text": "Conflict can be clean; argue with care, not contempt.",
        "mantra": "I debate cleanly and set edges.",
        "tiny_action": "Write it, then state my boundary once.",
        "journal_prompt": "What's my steel‑man of the opposing view?",
        "body_cue": "Bird‑dog — 2×8/side",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors friction • change.",
        "word_of_the_day": "arete",
        "word_meaning": "excellence of any kind",
        "trivia": "Blue whales are larger than any dinosaur.",
        "trivia_source": "NOAA — https://www.noaa.gov",
        "bipolar_self_check": "Sensation anchor: Name 5 things you feel physically; breathe out longer than in."
    },
    {
        "suit": "Spades",
        "rank": "6",
        "card_code": "spades_6",
        "card_label": "Six of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Slate Gray",
        "hex": "#708090",
        "lucky_number": 31,
        "rank_archetype": "flow • reciprocity",
        "quote": "Departure is a decision.",
        "oracle_text": "Move on mentally; don't live in old rooms.",
        "mantra": "I leave old rooms behind.",
        "tiny_action": "Do a 10‑minute brain dump; close the tab.",
        "journal_prompt": "What thought loop can I ferry across the river?",
        "body_cue": "Dead bug — 2×10",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors flow • reciprocity.",
        "word_of_the_day": "metanoia",
        "word_meaning": "transformative change of heart",
        "trivia": "Zero as a numeral emerged in ancient India.",
        "trivia_source": "Britannica — https://www.britannica.com",
        "bipolar_self_check": "Compare kindly: Do not compare to 'peak you'; compare to yesterday by 1% better."
    },
    {
        "suit": "Spades",
        "rank": "7",
        "card_code": "spades_7",
        "card_label": "Seven of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Charcoal",
        "hex": "#36454F",
        "lucky_number": 34,
        "rank_archetype": "faith • testing",
        "quote": "Attention is a currency; guard it.",
        "oracle_text": "Strategize; protect your edges.",
        "mantra": "I guard my attention.",
        "tiny_action": "Create a 'Not Today' list of 3 items.",
        "journal_prompt": "Where am I leaking attention?",
        "body_cue": "Standing hip hinges — 3×12",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors faith • testing.",
        "word_of_the_day": "ubuntu",
        "word_meaning": "I am because we are",
        "trivia": "Modern zippers date to Gideon Sundback (1913).",
        "trivia_source": "Smithsonian — https://www.si.edu",
        "bipolar_self_check": "Worry window: Contain worry to a 10‑minute slot; outside it, park thoughts on paper."
    },
    {
        "suit": "Spades",
        "rank": "8",
        "card_code": "spades_8",
        "card_label": "Eight of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Smoke Silver",
        "hex": "#C0C0C0",
        "lucky_number": 42,
        "rank_archetype": "power • discipline",
        "quote": "Fewer lanes, faster travel.",
        "oracle_text": "Clarity through constraint.",
        "mantra": "I free myself with constraints.",
        "tiny_action": "Work in one window only for 50 minutes.",
        "journal_prompt": "What rule today will free future‑me?",
        "body_cue": "Wall sit — 3×30s",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors power • discipline.",
        "word_of_the_day": "hiraeth",
        "word_meaning": "longing for a home that never was",
        "trivia": "Wurtzite BN can surpass diamond's hardness in cases.",
        "trivia_source": "MIT Tech Review — https://www.technologyreview.com",
        "bipolar_self_check": "Hope handle: Write one reason tomorrow can be workable; keep it visible."
    },
    {
        "suit": "Spades",
        "rank": "9",
        "card_code": "spades_9",
        "card_label": "Nine of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Graphite",
        "hex": "#3B3B3B",
        "lucky_number": 14,
        "rank_archetype": "ripening • integration",
        "quote": "Name the dragon; it shrinks.",
        "oracle_text": "Anxiety peaks before dawn—breathe and witness.",
        "mantra": "I witness fear and act small.",
        "tiny_action": "Name it, then take one tiny opposite action.",
        "journal_prompt": "What fear is a story, not a signal?",
        "body_cue": "Plank — 3×20–30s",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors ripening • integration.",
        "word_of_the_day": "apricity",
        "word_meaning": "warmth of the sun in winter",
        "trivia": "Leap day keeps calendars aligned with Earth's orbit.",
        "trivia_source": "Time and Date — https://www.timeanddate.com",
        "bipolar_self_check": "Clutter sweep: Clear one small surface; notice mental clarity after."
    },
    {
        "suit": "Spades",
        "rank": "10",
        "card_code": "spades_10",
        "card_label": "Ten of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Ash Mist",
        "hex": "#D3D3D3",
        "lucky_number": 1,
        "rank_archetype": "completion • legacy",
        "quote": "Closure is a skill.",
        "oracle_text": "End the mental saga—liberate bandwidth.",
        "mantra": "I close loops to free bandwidth.",
        "tiny_action": "Delete or archive 25 stale emails/files.",
        "journal_prompt": "Which identity am I overdue to shed?",
        "body_cue": "Side plank (knees) — 2×20s/side",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors completion • legacy.",
        "word_of_the_day": "pleroma",
        "word_meaning": "fullness; the whole",
        "trivia": "Cicadas emerge after 13 or 17 years.",
        "trivia_source": "USDA — https://www.usda.gov",
        "bipolar_self_check": "Gratitude triad: List 3 non‑grand things you're grateful for right now."
    },
    {
        "suit": "Spades",
        "rank": "Jack",
        "card_code": "spades_jack",
        "card_label": "Jack of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Pebble",
        "hex": "#B0A89F",
        "lucky_number": 13,
        "rank_archetype": "messenger • student",
        "quote": "A good question moves furniture in the mind.",
        "oracle_text": "Curious mind, sharp questions.",
        "mantra": "I ask catalytic questions.",
        "tiny_action": "Design a 15‑minute experiment or poll.",
        "journal_prompt": "What data would actually change my mind?",
        "body_cue": "Thoracic 'open book' — 2×10/side",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors messenger • student.",
        "word_of_the_day": "ataractic",
        "word_meaning": "producing calm",
        "trivia": "Some cave paintings are >40,000 years old.",
        "trivia_source": "UNESCO — https://whc.unesco.org",
        "bipolar_self_check": "Sleep plan: Set target lights‑out time; line up a pre‑sleep cue (book, stretch, music)."
    },
    {
        "suit": "Spades",
        "rank": "Queen",
        "card_code": "spades_queen",
        "card_label": "Queen of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Sandstone",
        "hex": "#D2B48C",
        "lucky_number": 2,
        "rank_archetype": "steward • receptivity",
        "quote": "Edges let gardens grow.",
        "oracle_text": "Boundaries are loving fences.",
        "mantra": "I speak less, mean more.",
        "tiny_action": "Use a one‑line 'no' with an alternative.",
        "journal_prompt": "Where can I say less and mean more?",
        "body_cue": "90/90 hip switches — 2×10",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors steward • receptivity.",
        "word_of_the_day": "noema",
        "word_meaning": "the object or content of thought",
        "trivia": "Hokusai's Great Wave used imported Prussian blue.",
        "trivia_source": "The Met Museum — https://www.metmuseum.org",
        "bipolar_self_check": "Relapse plan glance: Read your personal early‑warning list; choose one preemptive action."
    },
    {
        "suit": "Spades",
        "rank": "King",
        "card_code": "spades_king",
        "card_label": "King of Spades",
        "element": "Air",
        "suit_theme": "mind, clarity & boundaries",
        "direction": "East",
        "color": "Umber",
        "hex": "#635147",
        "lucky_number": 39,
        "rank_archetype": "sovereign • direction",
        "quote": "Leadership is choosing your constraints.",
        "oracle_text": "Decide cleanly; own the trade‑offs.",
        "mantra": "I decide and own the trade‑offs.",
        "tiny_action": "Make it by noon; document the why.",
        "journal_prompt": "What decision unblocks the week?",
        "body_cue": "Ankle dorsiflexion rocks — 2×15/side",
        "verbesque_verb": "Guard",
        "verbesque_cue": "Today, Guard your mind, clarity & boundaries in a way that honors sovereign • direction.",
        "word_of_the_day": "jetsam",
        "word_meaning": "items thrown overboard from a ship",
        "trivia": "Robot\" comes from Czech \"robota\".",
        "trivia_source": "Britannica — https://www.britannica.com",
        "bipolar_self_check": "Clinician note: If you hit 2 days at ≤3 or ≥8, consider notifying your clinician/support."
    }
];


